#!/usr/bin/env node
/**
 * build-catalog.mjs — scan an installed skills directory, keep the design skills,
 * and emit a catalog (JSON + Markdown) the /usedesign router consults.
 *
 * Usage: node scripts/build-catalog.mjs [skillsDir] [outDir]
 *   skillsDir defaults to ~/.claude/skills
 *   outDir    defaults to ./skills/usedesign
 *
 * A skill counts as "design" if its folder name starts with a design-family
 * prefix (ios / dec / flow- / wireframe) OR is in the curated cross-cutting set.
 * Reasoning/critique families (blind-*, si-*, nd-*, vd-*) are intentionally excluded.
 */

import { readdirSync, readFileSync, existsSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const skillsDir = process.argv[2] || join(homedir(), '.claude/skills');
const outDir = process.argv[3] || join(process.cwd(), 'skills/usedesign');

const FAMILY_PREFIXES = [
  ['ios', 'iOS (native)'],
  ['dec', 'Design Engineering Canon'],
  ['flow-', 'UX Flows'],
  ['wireframe', 'Wireframing'],
];

const CROSS_CUTTING = new Set([
  'accessibility-and-inclusive-design', 'accessibility-audit', 'anti-slop-design-law',
  'app-motion-and-animation', 'color-and-elevation', 'components-and-states', 'data-visualization',
  'ai-agent-case-study', 'case-study', 'case-study-design-decisions', 'case-study-story-map',
  'case-study-storytelling', 'case-study-writing',
  'design', 'design-tokens', 'dense-no-scroll-layout', 'ethical-design-and-dark-patterns',
  'grid-and-spacing', 'hallmark', 'iconography-and-imagery', 'inclusive-design',
  'interaction-and-motion', 'laws-of-ux-and-psychology', 'layout-and-composition',
  'macro-food-app-ui', 'make-interfaces-feel-better', 'polish', 'tufte', 'usability-heuristics',
  'userflow', 'ux-writing-and-content', 'visual-qa',
]);

// This router's own skill never catalogs itself.
const SELF = 'usedesign';

function familyOf(name) {
  for (const [prefix, family] of FAMILY_PREFIXES) if (name.startsWith(prefix)) return family;
  return 'Cross-cutting';
}

function isDesign(name) {
  if (name === SELF) return false;
  if (CROSS_CUTTING.has(name)) return true;
  return FAMILY_PREFIXES.some(([p]) => name.startsWith(p));
}

/** Pull the description line out of a SKILL.md frontmatter block; strip quotes. */
function readDescription(skillMdPath) {
  if (!existsSync(skillMdPath)) return null;
  const txt = readFileSync(skillMdPath, 'utf8');
  const fm = txt.split(/^---\s*$/m)[1];
  if (!fm) return null;
  const m = fm.match(/^description:\s*(.+?)\s*$/m);
  if (!m) return '';
  return m[1].replace(/^["']/, '').replace(/["']$/, '').trim();
}

const entries = [];
for (const name of readdirSync(skillsDir)) {
  const dir = join(skillsDir, name);
  let isDir = false;
  try { isDir = statSync(dir).isDirectory(); } catch { continue; } // statSync follows symlinks
  if (!isDir || !isDesign(name)) continue;
  const desc = readDescription(join(dir, 'SKILL.md'));
  if (desc === null) continue; // no SKILL.md → not a usable skill
  entries.push({ name, family: familyOf(name), description: desc });
}

entries.sort((a, b) => a.family.localeCompare(b.family) || a.name.localeCompare(b.name));

// Family display order (dispatchers first within each family reads naturally).
const FAMILY_ORDER = ['Cross-cutting', 'Design Engineering Canon', 'iOS (native)', 'UX Flows', 'Wireframing'];
const byFamily = new Map(FAMILY_ORDER.map((f) => [f, []]));
for (const e of entries) (byFamily.get(e.family) || byFamily.set(e.family, []).get(e.family)).push(e);

writeFileSync(join(outDir, 'catalog.json'), JSON.stringify(entries, null, 2) + '\n');

let md = `# Design skill catalog\n\nGenerated by \`scripts/build-catalog.mjs\` from your installed skills. ${entries.length} design skills across ${[...byFamily].filter(([, v]) => v.length).length} families. Regenerate after adding skills: \`node scripts/build-catalog.mjs\`.\n`;
for (const family of FAMILY_ORDER) {
  const list = byFamily.get(family) || [];
  if (!list.length) continue;
  md += `\n## ${family} (${list.length})\n\n`;
  for (const e of list) md += `- **${e.name}** — ${e.description}\n`;
}
writeFileSync(join(outDir, 'catalog.md'), md);

console.log(`Cataloged ${entries.length} design skills from ${skillsDir}`);
for (const family of FAMILY_ORDER) {
  const n = (byFamily.get(family) || []).length;
  if (n) console.log(`  ${family}: ${n}`);
}
